Add test to BookService, CategoryService, BookController and Category…
AntonBabychP1T/books-store-app pull request #14
Opened 2023-12-22 09:55 UTC by AntonBabychP1T

![Screenshot 2023-12-22 115314](https://github.com/AntonBabychP1T/books-store-app/assets/117450388/2a53d7db-eb01-4dac-b252-9c1bb2abbb84)
…Controller

2023-12-22 11:10 UTC, Rommelua requested changes
Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

![image](https://github.com/AntonBabychP1T/books-store-app/assets/20326858/9cff2e2a-351a-499e-b6f8-c91f20c3957c)

2023-12-24 11:46 UTC, Sanderfuck requested changes
![image](https://github.com/AntonBabychP1T/books-store-app/assets/63095184/8d7383ea-a2dc-4e95-8cea-186e500c3338)
Fix your tests at first

2023-12-24 11:46 UTC, Sanderfuck commented on src/test/java/store/bookstoreapp/controller/BookControllerTest.java
> +
```suggestion
```

2023-12-24 11:46 UTC, Sanderfuck commented on src/test/java/store/bookstoreapp/controller/BookControllerTest.java
> +        expected.add(thirdBook);
Create templates of entities and reuse it in every test what you need

2023-12-24 11:46 UTC, Sanderfuck commented on src/test/java/store/bookstoreapp/service/BookServiceTest.java
> +    private BookSpecificationBuilder bookSpecificationBuilder;
Manage your empty lines! Inject place after Mock

2023-12-24 11:46 UTC, Sanderfuck commented on src/test/java/store/bookstoreapp/service/BookServiceTest.java
> +        //then
Don`t needs comment in this case

2023-12-24 11:46 UTC, Sanderfuck commented on src/test/java/store/bookstoreapp/service/CategoryServiceTest.java
> +    private static final String VALID_NAME = "Valid name";
Keep one style of empty line after naming class

2023-12-24 11:47 UTC, Sanderfuck commented
Fix your checks!!!!

2023-12-25 13:37 UTC, merged